### ISSUE TITLE
@font-face

### ISSUE THREAD

**Issue by groenroos** [dciccale/css2stylus.js#10]
If you have multiple `@font-face` declarations, they will be merged into one and will stop functioning.

This;

    @font-face {
        font-family: myFirstFont;
        src: url(sansation_light.woff);
    }
    @font-face {
        font-family: mySecondFont;
        src: url(sansation.woff);
    }

Will be converted into this;

    @font-face
      font-family myFirstFont
      src url(sansation_light.woff)
      font-family mySecondFont
      src url(sansation.woff)

Meaning that `myFirstFont` will not be declared once the Stylus is converted back into CSS again.

**Comment by dciccale** [comment]
need to address this on a special case. TODO
