### ISSUE TITLE
some syntax errors after converting

### ISSUE THREAD

**Issue by jiyinyiyong** [dciccale/css2stylus.js#4]
And `css2stylus` is very nice. :+1: 

I found several syntax rules are probably not noticed and I got errors after converting:

* filter like this in Stylus:

```stylus
filter unquote('progid:DXImageTransform.Microsoft.BasicImage(rotation=1)')
```

if I write in CSS if would be wrong:

```css
filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1);
```

* dataUrl for bg images, but without quote

* -moz-document

```css
@-moz-document url-prefix() {
}
```

related: https://github.com/LearnBoost/stylus/commit/86ef56174bcecaa7d082d4835a283a9d30a8b9cd

**Comment by dciccale** [comment]
the related issue doesn't exist. closing if no updates on this
